10 casting between m32 and m64
acc-prac/bookish-carnival pull request #20
Opened 2022-07-16 06:35 UTC by ErfinderR

2022-07-16 06:56 UTC, ErfinderR commented on include/irregularia/mi.hpp
> +    //friend class multiple_int<2*BitWidth+1, typename width2<BackingStorage>::type> clausel
Is it really a recursion? So does the compiler create template classes from the "friend class ..." clausel until it reaches the class with width2<uint64_t>?

2022-07-16 07:01 UTC, ErfinderR commented on test/source/CMakeLists.txt
> -    decoding.cpp
Add this file again

2022-07-16 07:04 UTC, ErfinderR commented on test/source/CMakeLists.txt
> -    decoding.cpp
Solved [7d42dab](https://github.com/acc-prac/bookish-carnival/pull/20/commits/7d42dab517145ac67528289555f9393335bcbc38)

2022-07-16 15:53 UTC, bengsparks commented on include/irregularia/mi.hpp
> +    //friend class multiple_int<2*BitWidth+1, typename width2<BackingStorage>::type> clausel
This does not recurse. 
For instances of 

`multiple_int<BitWidth, BackingStorage>`

the contents of
`multiple_int<2*BitWidth+1, typename width2<BackingStorage>::type>`

are made available as a friend class. 
This kind of statement is a forward declaration, meaning the class referenced is not instantiated by this statement, so no recursion can I occur

(I think :tm:)

2022-07-16 16:00 UTC, bengsparks requested changes

2022-07-16 16:00 UTC, bengsparks commented on include/irregularia/mi.hpp
> +  multiple_int(multiple_int<SmallerBitWidth, SmallerBackingStorage> halfSizeMultipleInt)
Nice work!, we can use this to discuss the loopless + branchless implementation later

2022-07-16 16:00 UTC, bengsparks commented on test/source/casting.cpp
> +TEST(Casting, SignButNoCarryBits)
I assume the tests here are correct, because it is difficult to perform the addition in my head. But I fully trust that this works ^^

2022-07-17 09:19 UTC, ErfinderR commented on include/irregularia/mi.hpp
> +struct width2;
Solved with [a83f424](https://github.com/acc-prac/bookish-carnival/pull/20/commits/a83f4246f5d9a59d83557cf7c385898915099f1f)

2022-07-18 14:56 UTC, bengsparks commented
Superseded by #22

2022-07-18 14:56 UTC, closed without merging